= Экспериментальные погрешности

== Эксперимент 1.

#table(
  columns: (auto, auto, auto, auto, auto),
  stroke: none,
  inset: 10pt,
  align: horizon,
  table.hline(),
  table.header(
    [$P$], [$|P|$], [$Delta P$], [$|Delta P|$], [$delta$],
  ),
  table.hline(),
  table.vline(x: 0),
  table.vline(x: 1),
  table.vline(x: 2),
  table.vline(x: 3),
  table.vline(x: 4),
  table.vline(x: 5),
  [35], [], [11.66667], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [10], [], [13.33333], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [5], [], [18.33333], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [20], [23], [3.33333], [11.66667], [0.5],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [-], [], [-], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [40], [], [16.66667], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [30], [], [6.66667], [], [],
  table.hline()
)

#table(
  columns: (auto, auto, auto, auto, auto),
  stroke: none,
  inset: 10pt,
  align: horizon,
  table.hline(),
  table.header(
    [$I$], [$|I|$], [$Delta I$], [$|Delta I|$], [$delta$],
  ),
  table.hline(),
  table.vline(x: 0),
  table.vline(x: 1),
  table.vline(x: 2),
  table.vline(x: 3),
  table.vline(x: 4),
  table.vline(x: 5),
  [1.05], [], [0.316667], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [1.45], [], [0.0833333], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [1.05], [], [0.316667], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.725], [1], [0.641667], [0.572222], [0.418699],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [-], [], [-], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [3], [], [1.633333], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.925], [], [0.441667], [], [],
  table.hline()
)

#table(
  columns: (auto, auto, auto, auto, auto),
  stroke: none,
  inset: 10pt,
  align: horizon,
  table.hline(),
  table.header(
    [$P$], [$|P|$], [$Delta P$], [$|Delta P|$], [$delta$],
  ),
  table.hline(),
  table.vline(x: 0),
  table.vline(x: 1),
  table.vline(x: 2),
  table.vline(x: 3),
  table.vline(x: 4),
  table.vline(x: 5),
  [34], [], [0], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [34], [], [0], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [34.5], [], [0.5], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [34], [34], [0], [0.166667], [0.004902],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [-], [], [-], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [34], [], [0], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [33.5], [], [0.5], [], [],
  table.hline()
)

== Эксперимент 2.


#table(
  columns: (auto, auto, auto, auto, auto),
  stroke: none,
  inset: 10pt,
  align: horizon,
  table.hline(),
  table.header(
    [$x$], [$|x|$], [$Delta x$], [$|Delta x|$], [$delta$],
  ),
  table.hline(),
  table.vline(x: 0),
  table.vline(x: 1),
  table.vline(x: 2),
  table.vline(x: 3),
  table.vline(x: 4),
  table.vline(x: 5),
  [0.6], [], [0.35], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.5], [], [0.25], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.05], [], [0.2], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.1], [0.25], [0.15], [0.2], [0.8],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [-], [], [-], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.125], [], [0.125], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.125], [], [0.125], [], [],
  table.hline()
)

#table(
  columns: (auto, auto, auto, auto, auto),
  stroke: none,
  inset: 10pt,
  align: horizon,
  table.hline(),
  table.header(
    [$x_m$], [$|x_m|$], [$Delta x_m$], [$|Delta x_m|$], [$delta$],
  ),
  table.hline(),
  table.vline(x: 0),
  table.vline(x: 1),
  table.vline(x: 2),
  table.vline(x: 3),
  table.vline(x: 4),
  table.vline(x: 5),
  [0.65], [], [0.05], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [1.6], [], [1], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.35], [], [0.25], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.3], [0.6], [0.3], [0.35], [0.583],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [-], [], [-], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.375], [], [0.225], [], [],
  table.hline(start: 0, end: 1),
  table.hline(start: 2, end: 3),
  [0.325], [], [0.275], [], [],
  table.hline()
)
